/*
 * Protalko API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPresentation {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "visible_id")]
    pub visible_id: String,
}

impl UserPresentation {
    pub fn new(id: String, name: String, visible_id: String) -> UserPresentation {
        UserPresentation {
            id,
            name,
            visible_id,
        }
    }
}

